//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HuiYuan
    {
        public HuiYuan()
        {
            this.ShenQing = new HashSet<ShenQing>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string MyName { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string MyEmail { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LogonIP { get; set; }
        public string State { get; set; }
        public string BiaoShi { get; set; }
    
        public virtual ICollection<ShenQing> ShenQing { get; set; }
    }
}
