//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mess", Namespace="http://www.langben.com")]
    [System.SerializableAttribute()]
    public partial class Mess : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Message1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceIPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message1 {
            get {
                return this.Message1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Message1Field, value) != true)) {
                    this.Message1Field = value;
                    this.RaisePropertyChanged("Message1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SourceIP {
            get {
                return this.SourceIPField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceIPField, value) != true)) {
                    this.SourceIPField = value;
                    this.RaisePropertyChanged("SourceIP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.langben.com", ConfigurationName="ServiceReference2.MessageServiceSoap")]
    public interface MessageServiceSoap {
        
        // CODEGEN: 命名空间 http://www.langben.com 的元素名称 model 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.langben.com/MessageAdd", ReplyAction="*")]
        ConsoleApplication1.ServiceReference2.MessageAddResponse MessageAdd(ConsoleApplication1.ServiceReference2.MessageAddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.langben.com/MessageAdd", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference2.MessageAddResponse> MessageAddAsync(ConsoleApplication1.ServiceReference2.MessageAddRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageAddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageAdd", Namespace="http://www.langben.com", Order=0)]
        public ConsoleApplication1.ServiceReference2.MessageAddRequestBody Body;
        
        public MessageAddRequest() {
        }
        
        public MessageAddRequest(ConsoleApplication1.ServiceReference2.MessageAddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.langben.com")]
    public partial class MessageAddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication1.ServiceReference2.Mess model;
        
        public MessageAddRequestBody() {
        }
        
        public MessageAddRequestBody(ConsoleApplication1.ServiceReference2.Mess model) {
            this.model = model;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageAddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageAddResponse", Namespace="http://www.langben.com", Order=0)]
        public ConsoleApplication1.ServiceReference2.MessageAddResponseBody Body;
        
        public MessageAddResponse() {
        }
        
        public MessageAddResponse(ConsoleApplication1.ServiceReference2.MessageAddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.langben.com")]
    public partial class MessageAddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long MessageAddResult;
        
        public MessageAddResponseBody() {
        }
        
        public MessageAddResponseBody(long MessageAddResult) {
            this.MessageAddResult = MessageAddResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessageServiceSoapChannel : ConsoleApplication1.ServiceReference2.MessageServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceSoapClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference2.MessageServiceSoap>, ConsoleApplication1.ServiceReference2.MessageServiceSoap {
        
        public MessageServiceSoapClient() {
        }
        
        public MessageServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference2.MessageAddResponse ConsoleApplication1.ServiceReference2.MessageServiceSoap.MessageAdd(ConsoleApplication1.ServiceReference2.MessageAddRequest request) {
            return base.Channel.MessageAdd(request);
        }
        
        public long MessageAdd(ConsoleApplication1.ServiceReference2.Mess model) {
            ConsoleApplication1.ServiceReference2.MessageAddRequest inValue = new ConsoleApplication1.ServiceReference2.MessageAddRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference2.MessageAddRequestBody();
            inValue.Body.model = model;
            ConsoleApplication1.ServiceReference2.MessageAddResponse retVal = ((ConsoleApplication1.ServiceReference2.MessageServiceSoap)(this)).MessageAdd(inValue);
            return retVal.Body.MessageAddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference2.MessageAddResponse> ConsoleApplication1.ServiceReference2.MessageServiceSoap.MessageAddAsync(ConsoleApplication1.ServiceReference2.MessageAddRequest request) {
            return base.Channel.MessageAddAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference2.MessageAddResponse> MessageAddAsync(ConsoleApplication1.ServiceReference2.Mess model) {
            ConsoleApplication1.ServiceReference2.MessageAddRequest inValue = new ConsoleApplication1.ServiceReference2.MessageAddRequest();
            inValue.Body = new ConsoleApplication1.ServiceReference2.MessageAddRequestBody();
            inValue.Body.model = model;
            return ((ConsoleApplication1.ServiceReference2.MessageServiceSoap)(this)).MessageAddAsync(inValue);
        }
    }
}
