//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.App.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISysRoles")]
    public interface ISysRoles {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysRoles/GetPersonByBiaoShi", ReplyAction="http://tempuri.org/ISysRoles/GetPersonByBiaoShiResponse")]
        Common.ValueText[] GetPersonByBiaoShi(string biaoshi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISysRoles/GetPersonByBiaoShi", ReplyAction="http://tempuri.org/ISysRoles/GetPersonByBiaoShiResponse")]
        System.Threading.Tasks.Task<Common.ValueText[]> GetPersonByBiaoShiAsync(string biaoshi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISysRolesChannel : Langben.App.ServiceReference1.ISysRoles, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SysRolesClient : System.ServiceModel.ClientBase<Langben.App.ServiceReference1.ISysRoles>, Langben.App.ServiceReference1.ISysRoles {
        
        public SysRolesClient() {
        }
        
        public SysRolesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SysRolesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SysRolesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SysRolesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Common.ValueText[] GetPersonByBiaoShi(string biaoshi) {
            return base.Channel.GetPersonByBiaoShi(biaoshi);
        }
        
        public System.Threading.Tasks.Task<Common.ValueText[]> GetPersonByBiaoShiAsync(string biaoshi) {
            return base.Channel.GetPersonByBiaoShiAsync(biaoshi);
        }
    }
}
